apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  label:
    app: nginx-app-4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app-4
  template:
    metadata:
      labels:
        app: nginx-app-4

    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          limits:
            memory: "10Mi"
            cpu: "100m"
          requests:
            memory: "10Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
