apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-5
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination: 
    namespace: argo-app-5
    server: https://kubernetes.default.svc
  project: default
  source:
    path: myApp/app-5
    repoURL: https://github.com/starbiloz/argocd-app-of-apps.git
    targetRevision: HEAD
    